### ISSUE TITLE
[Bug] (preset-create-react-app) [webpack-dev-middleware] TypeError: Cannot read property 'length' of undefined when updating to SB 6.3 and WebPack 5.

### ISSUE THREAD

**Issue by enrique-ramirez** [storybookjs/presets#207]
### Describe the bug

From an existing storybook installation with SB 6.2 and WP 4, I'm attempting to update to SB 6.3 and WP 5.  I've added both `@storybook/builder-webpack5` and `@storybook/manager-webpack5`. This is a fairly straightforward installation without much customization to it. I keep getting the following error:

```
<i> [webpack-dev-middleware] wait until bundle finished
<e> [webpack-dev-middleware] TypeError: Cannot read property 'length' of undefined
<e>     at /myProject/node_modules/react-scripts/node_modules/webpack-manifest-plugin/lib/plugin.js:129:39
<e>     at Array.reduce (<anonymous>)
<e>     at ManifestPlugin.<anonymous> (/myProject/node_modules/react-scripts/node_modules/webpack-manifest-plugin/lib/plugin.js:116:26)
<e>     at _next1 (eval at create (/myProject/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:31:1)
<e>     at eval (eval at create (/myProject/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:69:1)
<e>     at emit (/myProject/node_modules/fork-ts-checker-webpack-plugin/lib/index.js:274:17)
<e>     at Hook.eval [as callAsync] (eval at create (/myProject/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:63:1)
<e>     at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/myProject/node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14)
<e>     at Compiler.emitAssets (/myProject/node_modules/webpack/lib/Compiler.js:862:19)
<e>     at /myProject/node_modules/webpack/lib/Watching.js:155:21
<e>     at processTicksAndRejections (internal/process/task_queues.js:77:11)
(node:15035) [DEP_WEBPACK_DEPRECATION_ARRAY_TO_SET] DeprecationWarning: Compilation.chunks was changed from Array to Set (using Array method 'reduce' is deprecated)
```

### Expected behavior

Storybook to start without issues.

### Environment

 - OS: MacOSX 11.4
 - Node.js version: 14.17.1
 - NPM version: 6.14.13

**Comment by tedesco8** [comment]
No solution yet?

**Comment by imki123** [comment]
FYI. https://github.com/storybookjs/storybook/issues/14789#issuecomment-868426385
main.js > `/* "@storybook/preset-create-react-app" */`
